version: "3"
services:
  caddy:
    image: abiosoft/caddy
    container_name: caddy
    ports:
      - 8880:8880
    volumes:
      - ./caddy/Caddyfile:/etc/Caddyfile:rw
      - ./caddy/.caddy:/root/.caddy:rw
      - ./caddy/www:/srv:rw

  postgres:
    image: postgres:alpine
    container_name: pg
    ports:
      - 5432:5432
    volumes:
      - ./pg/data:/var/lib/postgresql/data:rw
      - ./pg/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - ./redis/data:/data:rw
      # 若需要自定义配置的话，取消下面一行的注释
    #   - ./redis.conf:/usr/local/etc/redis/redis.conf

  redis_notify:
    image: redis:alpine
    container_name: redis_notify
    ports:
      - 6380:6379
    volumes:
      - ./redis_notify/data:/data:rw

#networks:
#  default:
#    external:
#      name: web-proxy
