version: '3'
services:
  nginx:
    image: nginx:alpine
    container_name: proxy
    ports:
      - 8880:8880
    volumes:
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    - ./nginx/log/:/var/log/nginx/:rw

  postgres:
    image: postgres:alpine
    container_name: pg
    ports:
      - 5432:5432
    volumes:
      - ./pg/data:/var/lib/postgresql/data:rw
      - ./pg/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - ./redis/data:/data:rw

#networks:
#  default:
#    external:
#      name: web-proxy